### ISSUE TITLE
'_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by sharpsan** [Patte1808/open_graph_parser#7]
`Performing hot reload...
Syncing files to device AOSP on IA Emulator...
Reloaded 1 of 615 libraries in 127ms.
E/flutter ( 4556): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter ( 4556): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 4556): #0      OpenGraphParser.getOpenGraphDataFromResponse (package:open_graph_parser/open_graph_parser.dart:40:5)
E/flutter ( 4556): #1      OpenGraphParser.getOpenGraphData (package:open_graph_parser/open_graph_parser.dart:15:12)
E/flutter ( 4556): <asynchronous suspension>
E/flutter ( 4556): #2      _MyHomePageState.getLinkData (package:linked/main.dart:66:38)
E/flutter ( 4556): #3      _MyHomePageState.build (package:linked/main.dart:73:5)
E/flutter ( 4556): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
E/flutter ( 4556): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
E/flutter ( 4556): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4556): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
E/flutter ( 4556): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4556): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4556): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
E/flutter ( 4556): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4556): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4556): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4556): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4556): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4556): #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
E/flutter ( 4556): #44     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
E/flutter ( 4556): #45    
`

**Comment by sharpsan** [comment]
### Flutter Doctor

`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.41.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
`

**Comment by jg-l** [comment]
The package on pub.dev is outdated. Author needs to publish latest. 

The package on pub.dev uses implicit map in line 20:
`var data = {}`

should be:

`Map<String, dynamic> data = new Map<String, dynamic>();`
